# PHP settings
[php]
version = "5.6"

# Scopes
[[scope]]
name = "main codebase"
path = "/home/samuel/dev/studypool/docker/legacy/qanda/protected"
includes = [
    "controllers",
    "models",
    "views"
]
